#!/bin/bash
# MAGA Protocol: Local Development Setup Script
# This script configures the local environment for Aider Service development

set -e

# Colors for output
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

echo -e "${BLUE}════════════════════════════════════════════════════════════${NC}"
echo -e "${BLUE}  MAGA Protocol: Aider Service Local Development Setup${NC}"
echo -e "${BLUE}════════════════════════════════════════════════════════════${NC}"
echo

# Default OpenAI API key (should be overridden)
DEFAULT_OPENAI_KEY="sk-demo-key-replace-with-real-key"

# Get user input for configuration
read -p "Enter your OpenAI API key (required): " OPENAI_KEY
OPENAI_KEY=${OPENAI_KEY:-$DEFAULT_OPENAI_KEY}

read -p "Enter MongoDB URI [mongodb://localhost:27017/aider-service]: " MONGO_URI
MONGO_URI=${MONGO_URI:-"mongodb://localhost:27017/aider-service"}

read -p "Enter GitHub token (optional): " GITHUB_TOKEN

read -p "Enter port number [3100]: " PORT
PORT=${PORT:-3100}

read -p "Enter default model [gpt-4]: " MODEL
MODEL=${MODEL:-"gpt-4"}

# Create .env file
ENV_FILE="../.env"

echo -e "${YELLOW}Creating .env file...${NC}"
cat > $ENV_FILE << EOL
# Aider Service Environment - Generated by MAGA setup script
# $(date)

# API Keys
OPENAI_API_KEY=$OPENAI_KEY
GITHUB_TOKEN=$GITHUB_TOKEN

# Database
MONGO_URI=$MONGO_URI

# Server Configuration
PORT=$PORT
NODE_ENV=development

# Aider Settings
DEFAULT_MODEL=$MODEL
EOL

echo -e "${GREEN}Environment configured successfully!${NC}"
echo

# Check MongoDB connection
echo -e "${YELLOW}Verifying MongoDB connection...${NC}"
if command -v mongosh &> /dev/null; then
  if mongosh "$MONGO_URI" --eval "db.adminCommand('ping')" &> /dev/null; then
    echo -e "${GREEN}MongoDB connection successful!${NC}"
  else
    echo -e "${YELLOW}Could not connect to MongoDB. Please check if your MongoDB server is running.${NC}"
    echo "You can start MongoDB with: brew services start mongodb-community"
  fi
else
  echo -e "${YELLOW}MongoDB shell (mongosh) not found. Skipping connection verification.${NC}"
  echo "Install MongoDB tools with: brew install mongodb-database-tools"
fi

echo
echo -e "${BLUE}════════════════════════════════════════════════════════════${NC}"
echo -e "${GREEN}Setup complete! You can now start the service with:${NC}"
echo -e "cd .. && npm run start"
echo -e "${BLUE}════════════════════════════════════════════════════════════${NC}"
