services:
  aider-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3100:3100"
    environment:
      - NODE_ENV=production
      - PORT=3100
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - GH_TOKEN=${GH_TOKEN}
    volumes:
      - ../../aider:/app/aider
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3100/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s

volumes:
  aider_repos: 